
AWSTemplateFormatVersion: 2010-09-09


Parameters:

  ECRImageName:
    Type: String

  DynamoDBTableName:
    Type: String

  SQSQueueName:
    Type: String


Resources:

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRImageName

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        -
          AttributeName: uuid
          AttributeType: B
        -
          AttributeName: timestamp
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: uuid
          KeyType: HASH
        -
          AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  SQSQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      QueueName: !Ref SQSQueueName
      VisibilityTimeout: 180
      MessageRetentionPeriod: 1209600
      DelaySeconds: 0
      MaximumMessageSize: 262144
      ReceiveMessageWaitTimeSeconds: 20
      SqsManagedSseEnabled: true


Outputs:

  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri

  SQSQueueUrl:
    Value: !GetAtt SQSQueue.QueueUrl
